Resolves #10 - add github action to build docker
IN-CORE/incore-docs pull request #16
Opened 2021-10-07 17:39 UTC by navarroc

Added github action workflow to build and push docker images

2021-10-15 23:59 UTC, ywkim312 commented
@navarroc I have a question. Maybe when we create a release, we will probably make a version number as incore doc version number. However, the tag number for api has been following the incore-services version number. In this PR, it doesn't really separates the api tag and incore tag, I guess. It shouldn't be a problem but just wanted to let you know.

2021-10-16 00:02 UTC, ywkim312 commented
Please ignore my previous comment about version number. It looks like you get the correct one and I missed that. I deleted my previous comment since it looked good.

2021-10-16 00:03 UTC, ywkim312 commented on .github/workflows/ci.yaml
> +        tags: "${{ env.DOC_TAGS }}"
tags and buildargs might not needed for building the image?

2021-10-19 16:52 UTC, vnarah2 requested changes

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +      - develop
we can also include 'release/*' here

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +  pull_request:
not mandatory, but we can also limit the PR branch list to the same in "push"

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +        elif [[ $GITHUB_REF =~ pull ]]; then
This condition can be optimized as below so it doesn't consider the branch names with word "pull" in it
```suggestion
        elif [[ "${{github.event_name}}" == "pull_request" ]]; then
            BRANCH="PR-${{github.event.pull_request.number}}"
```

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +      env:
remove all envs (same for "manual")

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +      with:
this build step only needs `workdir`, `name` and `no_push`  (same for "manual")

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +      env:
remove envs

2021-10-19 16:52 UTC, vnarah2 commented on .github/workflows/ci.yaml
> +        buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1
remove buildargs that are not used in dockerfile  (same for "manual")

2021-10-19 18:32 UTC, vnarah2 approved these changes

2021-10-20 13:32 UTC, merged