Updated notebook and markdown
IN-CORE/incore-docs pull request #200
Opened 2023-02-21 20:03 UTC by Vismayak

2023-02-22 19:04 UTC, navarroc commented
We're there any updates to the notebook? It's minor, but I think you can clear all the outputs cells and commit that or revert to the original unchanged notebook. The only notebooks we've included results are the testbed notebooks.

2023-02-22 19:11 UTC, navarroc commented
Can you update the description section of the markdown file too? We should change "The outputs of this analysis are a CSV file with maximum damage state from each hazard and the overall maximum damage." to 

"The outputs of this analysis are a CSV file with maximum damage state from each hazard and the overall maximum damage and a CSV with the combined damage probabilities from the three hazards.

2023-02-23 21:57 UTC, longshuicy commented on CHANGELOG.md
> +- Update combined damage analysis documentation [#194](https://github.com/IN-CORE/incore-docs/issues/194)
can you add the empty line back after this entry?

2023-02-23 22:01 UTC, longshuicy requested changes

2023-02-23 22:01 UTC, longshuicy commented on notebooks/combined_wind_wave_surge_building_dmg.ipynb
> +   "execution_count": 1,
I see weird execution count everywhere... haha how did you remove the output cell???
<img width="195" alt="image" src="https://user-images.githubusercontent.com/13950475/221040429-b0325493-5f2b-4c45-8651-228ae3b05dd6.png">


Could you try Kernel "restart and clear output"?
<img width="258" alt="image" src="https://user-images.githubusercontent.com/13950475/221040330-380bdd56-a6cb-4377-8508-0fd370338791.png">

2023-02-28 16:31 UTC, ywkim312 approved these changes

2023-02-28 16:34 UTC, merged