Reflects input changes to CBR
IN-CORE/incore-docs pull request #311
Opened 2023-12-07 22:35 UTC by Vismayak

2023-12-08 15:59 UTC, longshuicy commented
You might also want to update the workshop session 3 and 4 notebook to accept this new input in the PR? If it's not too much to do

2023-12-08 16:11 UTC, longshuicy requested changes

2023-12-08 16:11 UTC, longshuicy commented on notebooks/commercial_building_recovery.ipynb
>      "com_recovery.load_remote_input_dataset(\"mcs_failure\", mcs_failure)\n",
You might want to properly chain it with MCS so it doesn't confuse the user
```
Damage analysis --> MCS
 \               /
   \            /
    \         / 
    both into CBR
```

2023-12-08 16:24 UTC, longshuicy commented
> @longshuicy I already did update the workshop notebooks, thats the one where I pushed to main by mistake

That workshop notebook repos are private. Ya-Lan and Chris copied over the material to incore-docs so we can share it as a part of the documentation. Hence you might want to update it here. 

They should be under the path of `/manual_jb/content/workshops/20231115`. 

- You need to modify session 3 & session 4. Session 4 you can just add 
```
commercial_recovery.set_input_dataset("building_dmg", bldg_dmg_result)
```
- Session 3 I haven't tried. 
- Lastly, when notebooks updated, you would need to creating a zip file of them, and place it under `/workshops/20231115` to replace the outdated one. This is the place where we allow user to download the zipfile.

2023-12-11 16:57 UTC, ylyangtw commented
Tested session3 in zip file, it works. session 4 changes also look good.

Could you remove the __MACOSX in the zip file? 
![image](https://github.com/IN-CORE/incore-docs/assets/63822845/e94b3b81-0bb5-4b4a-8671-e45caa603e62)
If you simply use macos default to zip it, __MACOSX will be generated automatically. You will want to use command line in the terminal instead.

2023-12-11 19:12 UTC, navarroc approved these changes

2023-12-11 19:15 UTC, merged