Fix to the warning, using string sum instead
IN-CORE/incore-docs pull request #328
Opened 2024-01-11 17:00 UTC by Vismayak

2024-01-17 19:24 UTC, longshuicy requested changes
A few changes needed:
1. add changelog entry
2. keep the execution output
3. update the zip if you updated anything in the notebook

Also it would be help that you can pin-point which line did you change?

2024-02-02 15:32 UTC, longshuicy requested changes
- [x] Could you fix the conflict 
- [x] Code works well. But when I unzip I noticed there are additional macos files
<img width="796" alt="image" src="https://github.com/IN-CORE/incore-docs/assets/13950475/91a2f232-2bdf-48fc-99b8-6611a253ebcd">

- [ ] In the zip file; the notebook shouldn't contain any output cells. The output cell is only for notebooks under content/notebooks (for displaying on the documentation site)

2024-02-02 15:48 UTC, navarroc commented
Checked the output against the previous and everything looks good. If you can address the issues @longshuicy identified, then I think it'll be ready to merge.

2024-02-02 17:36 UTC, Vismayak commented on CHANGELOG.md
> +## [Unreleased] -
All done, sorry for the stupid mistakes Chen! I am gonna get the changelog tatoo soon

2024-02-02 17:37 UTC, Vismayak commented
@navarroc @longshuicy I think it is ready now to be merged :)

2024-02-02 19:10 UTC, Vismayak commented
@navarroc removed 👍

2024-02-02 19:14 UTC, navarroc commented
Sorry to nitpick, but can you remove the hidden .DS_Store file in the Galveston zip file? Thank you!

2024-02-02 19:38 UTC, navarroc commented
Can you remove the __MACOSX folder in the zips?

2024-02-02 20:22 UTC, Rashmil-1999 approved these changes

2024-02-02 20:35 UTC, longshuicy approved these changes
zipfiles look good now

2024-02-02 20:35 UTC, merged