New input parameter for pop dislocation
IN-CORE/incore-docs pull request #383
Opened 2024-04-26 19:26 UTC by Vismayak

2024-04-26 19:44 UTC, navarroc commented
Can you point this at the release branch?

2024-04-26 20:00 UTC, navarroc commented on manual_jb/content/analyses/populationdislocation.md
>  **Input Datasets**
For input datasets, can you add ergo:buildingDamageVer6 and ergo:buildingDamageVer7 as valid inputs?

2024-04-26 23:29 UTC, navarroc requested changes
Please point this PR at the release branch

2024-04-29 16:53 UTC, longshuicy approved these changes

2024-04-29 16:53 UTC, merged