60 fix dfr3 visualization in pyincore viz example notebook
IN-CORE/incore-docs pull request #61
Opened 2022-01-26 22:17 UTC by ywkim312

The visualization of DFR3 has been updated. Those are last two cells of the pyincore-viz-example notebook. To test it, you have to change the incore client to dev instance.

2022-02-01 21:33 UTC, longshuicy approved these changes

2022-02-02 22:05 UTC, navarroc approved these changes

2022-02-02 22:20 UTC, navarroc commented
Let's wait to merge this, we need to merge the other pyincore-viz-example first since it's a bigger change.

2022-02-02 22:21 UTC, navarroc requested changes
Unapproving so we don't accidentally merge this. We should merge the other pyincore-viz notebook change first. Then update this one since it's a small change.

2022-02-02 22:38 UTC, ywkim312 commented
This will be implemented in the other PR. PR #54

2022-02-02 22:38 UTC, closed without merging